Html.text "Documents"
Html.text "Videos"
Html.text "Music"
Html.text "Pictures"
Html.text " "
Html.text "Documents"
Html.text "Videos"
Html.text "Music"
Html.text "Pictures"
Html.text " "
Html.text "Right"
Html.text "Up"
Html.text "Left"
Html.text " "
Html.text "Documents"
Html.text "Videos"
Html.text "Music"
Html.text "Pictures"
Html.text " "
Html.text "Documents"
Html.text "Videos"
Html.text "Music"
Html.text "Pictures"
Html.text " "
Html.text "Documents"
Html.text "Videos"
Html.text "Music"
Html.text "Pictures"
Html.text " "
Html.text "Documents"
Html.text "Videos"
Html.text "Music"
Html.text "Pictures"
Html.text " "
Html.text "Documents"
Html.text "Videos"
Html.text "Music"
Html.text "Pictures"
Html.text " "
Html.text "Documents"
Html.text "Videos"
Html.text "Music"
Html.text "Pictures"
Html.text " "
Html.text "Documents"
Html.text "Videos"
Html.text "Music"
Html.text "Pictures"
Html.text " "
Html.text "Documents"
Html.text "Videos"
Html.text "Music"
Html.text "Pictures"
Html.hr []
Html.text "Tabs"
Html.text " Reset all filters "
Html.text " Remember me "
Html.input [
    prop.type' "checkbox"
]
Html.text " mojs "
Html.text " daniellowtw/infBoard "
Html.text " jgthms.github.io "
Html.text " minireset.css "
Html.text " marksheet "
Html.text " bulma "
Html.text "Forks"
Html.text "Sources"
Html.text "Private"
Html.text "Public"
Html.text "All"
Html.input [
    prop.classes [ "input"; "is-small" ]
    prop.type' "text"
    prop.placeholder "Search"
]
Html.text " Repositories "
Html.hr []
Html.text "Panel"
Html.text "86"
Html.text "…"
Html.text "47"
Html.text "46"
Html.text "45"
Html.text "…"
Html.text "1"
Html.text "Next page"
Html.text "Previous"
Html.text " "
Html.text "86"
Html.text "…"
Html.text "47"
Html.text "46"
Html.text "45"
Html.text "…"
Html.text "1"
Html.text "Next page"
Html.text "Previous"
Html.hr []
Html.text "Pagination"
Html.text "Download"
Html.text "Tweet"
Html.text " Github "
Html.text "0.4.3"
Html.text "version "
Html.hr [
    prop.className "navbar-divider"
]
Html.text " Discover "
Html.text " Overview "
Html.text " Docs "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-logo.png"
    prop.alt "Bulma: a modern CSS framework based on Flexbox"
    prop.width 112
    prop.height 28
]
Html.text "Transparent"
Html.text " "
Html.text "Download"
Html.text "Tweet"
Html.text " Twitter "
Html.text " Github "
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text "Subscribe"
Html.text "Stay up to date!"
Html.hr [
    prop.className "navbar-divider"
]
Html.text " More posts "
Html.text "Blog launched, new responsive columns, new helpers"
Html.text "09 Feb 2016"
Html.text "Metro UI CSS grid with Bulma tiles"
Html.text "11 Apr 2016"
Html.text "New field element (for better controls)"
Html.text "10 Mar 2017"
Html.text " Blog "
Html.text "0.4.3"
Html.text "version "
Html.hr [
    prop.className "navbar-divider"
]
Html.text " Layout "
Html.text " Components "
Html.text " Elements "
Html.text " Form "
Html.text " Grid "
Html.text " Modifiers "
Html.text " Overview "
Html.text " Docs "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-logo.png"
    prop.alt "Bulma: a modern CSS framework based on Flexbox"
    prop.width 112
    prop.height 28
]
Html.text " "
Html.text "Download"
Html.text "Tweet"
Html.text " Twitter "
Html.text " Github "
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text "Subscribe"
Html.text "Stay up to date!"
Html.hr [
    prop.className "navbar-divider"
]
Html.text " More posts "
Html.text "Blog launched, new responsive columns, new helpers"
Html.text "09 Feb 2016"
Html.text "Metro UI CSS grid with Bulma tiles"
Html.text "11 Apr 2016"
Html.text "New field element (for better controls)"
Html.text "10 Mar 2017"
Html.text " Blog "
Html.text "0.4.3"
Html.text "version "
Html.hr [
    prop.className "navbar-divider"
]
Html.text " Layout "
Html.text " Components "
Html.text " Elements "
Html.text " Form "
Html.text " Grid "
Html.text " Modifiers "
Html.text " Overview "
Html.text " Docs "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-logo.png"
    prop.alt "Bulma: a modern CSS framework based on Flexbox"
    prop.width 112
    prop.height 28
]
Html.text " "
Html.text "Download"
Html.text "Tweet"
Html.text " Twitter "
Html.text " Github "
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text "Subscribe"
Html.text "Stay up to date!"
Html.hr [
    prop.className "navbar-divider"
]
Html.text " More posts "
Html.text "Blog launched, new responsive columns, new helpers"
Html.text "09 Feb 2016"
Html.text "Metro UI CSS grid with Bulma tiles"
Html.text "11 Apr 2016"
Html.text "New field element (for better controls)"
Html.text "10 Mar 2017"
Html.text " Blog "
Html.text "0.4.3"
Html.text "version "
Html.hr [
    prop.className "navbar-divider"
]
Html.text " Layout "
Html.text " Components "
Html.text " Elements "
Html.text " Form "
Html.text " Grid "
Html.text " Modifiers "
Html.text " Overview "
Html.text " Docs "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-logo.png"
    prop.alt "Bulma: a modern CSS framework based on Flexbox"
    prop.width 112
    prop.height 28
]
Html.text " "
Html.text "Download"
Html.text "Tweet"
Html.text " Twitter "
Html.text " Github "
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text "Subscribe"
Html.text "Stay up to date!"
Html.hr [
    prop.className "navbar-divider"
]
Html.text " More posts "
Html.text "Blog launched, new responsive columns, new helpers"
Html.text "09 Feb 2016"
Html.text "Metro UI CSS grid with Bulma tiles"
Html.text "11 Apr 2016"
Html.text "New field element (for better controls)"
Html.text "10 Mar 2017"
Html.text " Blog "
Html.text "0.4.3"
Html.text "version "
Html.hr [
    prop.className "navbar-divider"
]
Html.text " Layout "
Html.text " Components "
Html.text " Elements "
Html.text " Form "
Html.text " Grid "
Html.text " Modifiers "
Html.text " Overview "
Html.text " Docs "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-logo.png"
    prop.alt "Bulma: a modern CSS framework based on Flexbox"
    prop.width 112
    prop.height 28
]
Html.text " "
Html.text "Download"
Html.text "Tweet"
Html.text " Twitter "
Html.text " Github "
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text "Subscribe"
Html.text "Stay up to date!"
Html.hr [
    prop.className "navbar-divider"
]
Html.text " More posts "
Html.text "Blog launched, new responsive columns, new helpers"
Html.text "09 Feb 2016"
Html.text "Metro UI CSS grid with Bulma tiles"
Html.text "11 Apr 2016"
Html.text "New field element (for better controls)"
Html.text "10 Mar 2017"
Html.text " Blog "
Html.text "0.4.3"
Html.text "version "
Html.hr [
    prop.className "navbar-divider"
]
Html.text " Layout "
Html.text " Components "
Html.text " Elements "
Html.text " Form "
Html.text " Grid "
Html.text " Modifiers "
Html.text " Overview "
Html.text " Docs "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-logo.png"
    prop.alt "Bulma: a modern CSS framework based on Flexbox"
    prop.width 112
    prop.height 28
]
Html.text " "
Html.text "Download"
Html.text "Tweet"
Html.text " Twitter "
Html.text " Github "
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text "Subscribe"
Html.text "Stay up to date!"
Html.hr [
    prop.className "navbar-divider"
]
Html.text " More posts "
Html.text "Blog launched, new responsive columns, new helpers"
Html.text "09 Feb 2016"
Html.text "Metro UI CSS grid with Bulma tiles"
Html.text "11 Apr 2016"
Html.text "New field element (for better controls)"
Html.text "10 Mar 2017"
Html.text " Blog "
Html.text "0.4.3"
Html.text "version "
Html.hr [
    prop.className "navbar-divider"
]
Html.text " Layout "
Html.text " Components "
Html.text " Elements "
Html.text " Form "
Html.text " Grid "
Html.text " Modifiers "
Html.text " Overview "
Html.text " Docs "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-logo.png"
    prop.alt "Bulma: a modern CSS framework based on Flexbox"
    prop.width 112
    prop.height 28
]
Html.text " "
Html.text "Download"
Html.text "Tweet"
Html.text " Twitter "
Html.text " Github "
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text "Subscribe"
Html.text "Stay up to date!"
Html.hr [
    prop.className "navbar-divider"
]
Html.text " More posts "
Html.text "Blog launched, new responsive columns, new helpers"
Html.text "09 Feb 2016"
Html.text "Metro UI CSS grid with Bulma tiles"
Html.text "11 Apr 2016"
Html.text "New field element (for better controls)"
Html.text "10 Mar 2017"
Html.text " Blog "
Html.text "0.4.3"
Html.text "version "
Html.hr [
    prop.className "navbar-divider"
]
Html.text " Layout "
Html.text " Components "
Html.text " Elements "
Html.text " Form "
Html.text " Grid "
Html.text " Modifiers "
Html.text " Overview "
Html.text " Docs "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-logo.png"
    prop.alt "Bulma: a modern CSS framework based on Flexbox"
    prop.width 112
    prop.height 28
]
Html.text " "
Html.text "Download"
Html.text "Tweet"
Html.text " Twitter "
Html.text " Github "
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text "Subscribe"
Html.text "Stay up to date!"
Html.hr [
    prop.className "navbar-divider"
]
Html.text " More posts "
Html.text "Blog launched, new responsive columns, new helpers"
Html.text "09 Feb 2016"
Html.text "Metro UI CSS grid with Bulma tiles"
Html.text "11 Apr 2016"
Html.text "New field element (for better controls)"
Html.text "10 Mar 2017"
Html.text " Blog "
Html.text "0.4.3"
Html.text "version "
Html.hr [
    prop.className "navbar-divider"
]
Html.text " Layout "
Html.text " Components "
Html.text " Elements "
Html.text " Form "
Html.text " Grid "
Html.text " Modifiers "
Html.text " Overview "
Html.text " Docs "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-logo.png"
    prop.alt "Bulma: a modern CSS framework based on Flexbox"
    prop.width 112
    prop.height 28
]
Html.text " "
Html.text "Download"
Html.text "Tweet"
Html.text " Twitter "
Html.text " Github "
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text "Subscribe"
Html.text "Stay up to date!"
Html.hr [
    prop.className "navbar-divider"
]
Html.text " More posts "
Html.text "Blog launched, new responsive columns, new helpers"
Html.text "09 Feb 2016"
Html.text "Metro UI CSS grid with Bulma tiles"
Html.text "11 Apr 2016"
Html.text "New field element (for better controls)"
Html.text "10 Mar 2017"
Html.text " Blog "
Html.text "0.4.3"
Html.text "version "
Html.hr [
    prop.className "navbar-divider"
]
Html.text " Layout "
Html.text " Components "
Html.text " Elements "
Html.text " Form "
Html.text " Grid "
Html.text " Modifiers "
Html.text " Overview "
Html.text " Docs "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-logo.png"
    prop.alt "Bulma: a modern CSS framework based on Flexbox"
    prop.width 112
    prop.height 28
]
Html.text " "
Html.text "Download"
Html.text "Tweet"
Html.text " Twitter "
Html.text " Github "
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text "Subscribe"
Html.text "Stay up to date!"
Html.hr [
    prop.className "navbar-divider"
]
Html.text " More posts "
Html.text "Blog launched, new responsive columns, new helpers"
Html.text "09 Feb 2016"
Html.text "Metro UI CSS grid with Bulma tiles"
Html.text "11 Apr 2016"
Html.text "New field element (for better controls)"
Html.text "10 Mar 2017"
Html.text " Blog "
Html.text "0.4.3"
Html.text "version "
Html.hr [
    prop.className "navbar-divider"
]
Html.text " Layout "
Html.text " Components "
Html.text " Elements "
Html.text " Form "
Html.text " Grid "
Html.text " Modifiers "
Html.text " Overview "
Html.text " Docs "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-logo.png"
    prop.alt "Bulma: a modern CSS framework based on Flexbox"
    prop.width 112
    prop.height 28
]
Html.text " "
Html.text "Download"
Html.text "Tweet"
Html.text " Twitter "
Html.text " Github "
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text "Subscribe"
Html.text "Stay up to date!"
Html.hr [
    prop.className "navbar-divider"
]
Html.text " More posts "
Html.text "Blog launched, new responsive columns, new helpers"
Html.text "09 Feb 2016"
Html.text "Metro UI CSS grid with Bulma tiles"
Html.text "11 Apr 2016"
Html.text "New field element (for better controls)"
Html.text "10 Mar 2017"
Html.text " Blog "
Html.text "0.4.3"
Html.text "version "
Html.hr [
    prop.className "navbar-divider"
]
Html.text " Layout "
Html.text " Components "
Html.text " Elements "
Html.text " Form "
Html.text " Grid "
Html.text " Modifiers "
Html.text " Overview "
Html.text " Docs "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-logo.png"
    prop.alt "Bulma: a modern CSS framework based on Flexbox"
    prop.width 112
    prop.height 28
]
Html.hr []
Html.text "Navbar"
Html.text "Cancel"
Html.text "Save changes"
Html.text " Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. "
Html.text "Modal title"
Html.text "Launch example modal"
Html.hr []
Html.text "Modal"
Html.text ". "
Html.text "eleifend lacus"
Html.text " efficitur. Aenean ac "
Html.text "felis venenatis"
Html.text ", tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum "
Html.text "Pellentesque risus mi"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
Html.text " Dark "
Html.text ". "
Html.text "eleifend lacus"
Html.text " efficitur. Aenean ac "
Html.text "felis venenatis"
Html.text ", tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum "
Html.text "Pellentesque risus mi"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
Html.text " Light "
Html.text ". "
Html.text "eleifend lacus"
Html.text " efficitur. Aenean ac "
Html.text "felis venenatis"
Html.text ", tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum "
Html.text "Pellentesque risus mi"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
Html.text " Black "
Html.text ". "
Html.text "eleifend lacus"
Html.text " efficitur. Aenean ac "
Html.text "felis venenatis"
Html.text ", tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum "
Html.text "Pellentesque risus mi"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
Html.text " White "
Html.text ". "
Html.text "eleifend lacus"
Html.text " efficitur. Aenean ac "
Html.text "felis venenatis"
Html.text ", tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum "
Html.text "Pellentesque risus mi"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
Html.text " Danger "
Html.text ". "
Html.text "eleifend lacus"
Html.text " efficitur. Aenean ac "
Html.text "felis venenatis"
Html.text ", tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum "
Html.text "Pellentesque risus mi"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
Html.text " Warning "
Html.text ". "
Html.text "eleifend lacus"
Html.text " efficitur. Aenean ac "
Html.text "felis venenatis"
Html.text ", tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum "
Html.text "Pellentesque risus mi"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
Html.text " Success "
Html.text ". "
Html.text "eleifend lacus"
Html.text " efficitur. Aenean ac "
Html.text "felis venenatis"
Html.text ", tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum "
Html.text "Pellentesque risus mi"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
Html.text " Info "
Html.text ". "
Html.text "eleifend lacus"
Html.text " efficitur. Aenean ac "
Html.text "felis venenatis"
Html.text ", tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum "
Html.text "Pellentesque risus mi"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
Html.text " Link "
Html.text ". "
Html.text "eleifend lacus"
Html.text " efficitur. Aenean ac "
Html.text "felis venenatis"
Html.text ", tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum "
Html.text "Pellentesque risus mi"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
Html.text " Primary "
Html.text ". "
Html.text "eleifend lacus"
Html.text " efficitur. Aenean ac "
Html.text "felis venenatis"
Html.text ", tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum "
Html.text "Pellentesque risus mi"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
Html.text " Message "
Html.hr []
Html.text "Message"
Html.text "Balance"
Html.text "Transfers"
Html.text "Payments"
Html.text " Transactions "
Html.text "Authentication"
Html.text "Cloud Storage Environment Settings"
Html.text "Invitations"
Html.text "Add a member"
Html.text "Plugins"
Html.text "Members"
Html.text "Manage Your Team"
Html.text "Team Settings"
Html.text " Administration "
Html.text "Customers"
Html.text "Dashboard"
Html.text " General "
Html.hr []
Html.text "Menu"
Html.text "Post comment"
Html.img [
    prop.src "https://s3.amazonaws.com/uifaces/faces/twitter/zeldman/128.jpg"
]
Html.text " · 2 hrs"
Html.text "Reply"
Html.text " · "
Html.text "Like"
Html.text " "
Html.text " Sed convallis scelerisque mauris, non pulvinar nunc mattis vel. Maecenas varius felis sit amet magna vestibulum euismod malesuada cursus libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus lacinia non nisl id feugiat. "
Html.text " "
Html.text "Kayli Eunice "
Html.img [
    prop.src "https://bulma.io/images/placeholders/96x96.png"
]
Html.text " Morbi vitae diam et purus tincidunt porttitor vel vitae augue. Praesent malesuada metus sed pharetra euismod. Cras tellus odio, tincidunt iaculis diam non, porta aliquet tortor. "
Html.text " Vivamus quis semper metus, non tincidunt dolor. Vivamus in mi eu lorem cursus ullamcorper sit amet nec massa. "
Html.text " · 2 hrs"
Html.text "Reply"
Html.text " · "
Html.text "Like"
Html.text " "
Html.text " Donec sollicitudin urna eget eros malesuada sagittis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam blandit nisl a nulla sagittis, a lobortis leo feugiat. "
Html.text " "
Html.text "Sean Brown"
Html.img [
    prop.src "https://bulma.io/images/placeholders/96x96.png"
]
Html.text " · 3 hrs"
Html.text "Reply"
Html.text " · "
Html.text "Like"
Html.text " "
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis porta eros lacus, nec ultricies elit blandit non. Suspendisse pellentesque mauris sit amet dolor blandit rutrum. Nunc in tempus turpis. "
Html.text " "
Html.text "Barbara Middleton"
Html.img [
    prop.src "https://s3.amazonaws.com/uifaces/faces/twitter/zeldman/128.jpg"
]
Html.text "Nesting"
Html.hr []
Html.text " Press enter to submit "
Html.input [
    prop.type' "checkbox"
]
Html.text "Post comment"
Html.img [
    prop.src "https://s3.amazonaws.com/uifaces/faces/twitter/zeldman/128.jpg"
]
Html.hr []
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis. "
Html.text " "
Html.text "31m"
Html.text "@johnsmith"
Html.text "John Smith"
Html.img [
    prop.src "https://s3.amazonaws.com/uifaces/faces/twitter/zeldman/128.jpg"
]
Html.hr []
Html.text "Media Object"
Html.hr []
Html.text "789"
Html.text "Likes"
Html.text "456K"
Html.text "Followers"
Html.text "123"
Html.text "Following"
Html.text "3,456"
Html.text "Tweets"
Html.hr []
Html.text "Contact"
Html.text "Reservations"
Html.img [
    prop.src "https://bulma.io/images/bulma-type.png"
    prop.alt ""
    prop.style "height: 30px;"
]
Html.text "Menu"
Html.text "Home"
Html.hr []
Html.text "789"
Html.text "Likes"
Html.text "456K"
Html.text "Followers"
Html.text "123"
Html.text "Following"
Html.text "3,456"
Html.text "Tweets"
Html.hr []
Html.text "New"
Html.text "Deleted"
Html.text "Drafts"
Html.text "Published"
Html.text "All"
Html.text " Search "
Html.input [
    prop.className "input"
    prop.type' "text"
    prop.placeholder "Find a post"
]
Html.text " posts "
Html.text "123"
Html.hr []
Html.text "Level"
Html.text " This is a link "
Html.hr [
    prop.className "dropdown-divider"
]
Html.text " instead."
Html.text ">"
Html.text "div"
Html.text "<"
Html.text "You simply need to use a "
Html.hr [
    prop.className "dropdown-divider"
]
Html.text " within the dropdown menu."
Html.text "any type of content"
Html.text "You can insert "
Html.text "Content"
Html.text " With a divider "
Html.hr [
    prop.className "dropdown-divider"
]
Html.text " Other dropdown item "
Html.text " Active dropdown item "
Html.text " Other dropdown item "
Html.text " Dropdown item "
Html.text "Dropdown button"
Html.hr []
Html.text "Dropdown"
Html.text "Delete"
Html.text "Edit"
Html.text "Save"
Html.text "11:09 PM - 1 Jan 2016"
Html.text " "
Html.text "#responsive"
Html.text "#css"
Html.text ". "
Html.text "@bulmaio"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec iaculis mauris. "
Html.text " Component "
Html.text "11:09 PM - 1 Jan 2016"
Html.text " "
Html.text "#responsive"
Html.text "#css"
Html.text ". "
Html.text "@bulmaio"
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec iaculis mauris. "
Html.text "@johnsmith"
Html.text "John Smith"
Html.img [
    prop.src "https://source.unsplash.com/random/96x96"
    prop.alt "Image"
]
Html.img [
    prop.src "https://source.unsplash.com/random/800x600"
    prop.alt "Image"
]
Html.hr []
Html.text "Cards"
Html.text " "
Html.text "Layout"
Html.text "Components"
Html.text "Elements"
Html.text "Grid"
Html.text "Modifiers"
Html.text "Overview"
Html.text " Subtitle "
Html.text " Title "
Html.text "Download"
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text " Documentation "
Html.text " Examples "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-type-white.png"
    prop.alt "Logo"
]
Html.text " "
Html.text "Layout"
Html.text "Components"
Html.text "Elements"
Html.text "Grid"
Html.text "Modifiers"
Html.text "Overview"
Html.text " Subtitle "
Html.text " Title "
Html.text "Download"
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text " Documentation "
Html.text " Examples "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-type-white.png"
    prop.alt "Logo"
]
Html.text " "
Html.text "Layout"
Html.text "Components"
Html.text "Elements"
Html.text "Grid"
Html.text "Modifiers"
Html.text "Overview"
Html.text " Subtitle "
Html.text " Title "
Html.text "Download"
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text " Documentation "
Html.text " Examples "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-type-white.png"
    prop.alt "Logo"
]
Html.text " "
Html.text "Layout"
Html.text "Components"
Html.text "Elements"
Html.text "Grid"
Html.text "Modifiers"
Html.text "Overview"
Html.text " Subtitle "
Html.text " Title "
Html.text "Download"
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text " Documentation "
Html.text " Examples "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-type-white.png"
    prop.alt "Logo"
]
Html.text " "
Html.text "Layout"
Html.text "Components"
Html.text "Elements"
Html.text "Grid"
Html.text "Modifiers"
Html.text "Overview"
Html.text " Subtitle "
Html.text " Title "
Html.text "Download"
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text " Documentation "
Html.text " Examples "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-type-white.png"
    prop.alt "Logo"
]
Html.text " "
Html.text "Layout"
Html.text "Components"
Html.text "Elements"
Html.text "Grid"
Html.text "Modifiers"
Html.text "Overview"
Html.text " Subtitle "
Html.text " Title "
Html.text "Download"
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text " Documentation "
Html.text " Examples "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-type-white.png"
    prop.alt "Logo"
]
Html.text " "
Html.text "Layout"
Html.text "Components"
Html.text "Elements"
Html.text "Grid"
Html.text "Modifiers"
Html.text "Overview"
Html.text " Subtitle "
Html.text " Title "
Html.text "Download"
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text " Documentation "
Html.text " Examples "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-type-white.png"
    prop.alt "Logo"
]
Html.text " "
Html.text "Layout"
Html.text "Components"
Html.text "Elements"
Html.text "Grid"
Html.text "Modifiers"
Html.text "Overview"
Html.text " Subtitle "
Html.text " Title "
Html.text "Download"
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text " Documentation "
Html.text " Examples "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-type-white.png"
    prop.alt "Logo"
]
Html.text " "
Html.text "Layout"
Html.text "Components"
Html.text "Elements"
Html.text "Grid"
Html.text "Modifiers"
Html.text "Overview"
Html.text " Subtitle "
Html.text " Title "
Html.text "Download"
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text " Documentation "
Html.text " Examples "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-type-white.png"
    prop.alt "Logo"
]
Html.text " "
Html.text "Layout"
Html.text "Components"
Html.text "Elements"
Html.text "Grid"
Html.text "Modifiers"
Html.text "Overview"
Html.text " Subtitle "
Html.text " Title "
Html.text "Download"
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text " Documentation "
Html.text " Examples "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-type-white.png"
    prop.alt "Logo"
]
Html.text " "
Html.text "Layout"
Html.text "Components"
Html.text "Elements"
Html.text "Grid"
Html.text "Modifiers"
Html.text "Overview"
Html.text " Subtitle "
Html.text " Title "
Html.text "Download"
Html.text "Side projects to enhance Bulma"
Html.text " "
Html.text "Extensions"
Html.text " More "
Html.text " Documentation "
Html.text " Examples "
Html.text " Home "
Html.img [
    prop.src "https://bulma.io/images/bulma-type-white.png"
    prop.alt "Logo"
]
Html.hr []
Html.text "Hero"
Html.text "Breadcrumb"
Html.text "Components"
Html.text "Documentation"
Html.text "Bulma"
Html.hr []
Html.text "Breadcrumb"
Html.text "Documentation"
Html.text "Community"
Html.text "Open Source"
Html.text "Web Design"
Html.text "Flexbox"
Html.text "CSS"
Html.text "Technology"
Html.text "on gitter"
Html.text "chat"
Html.text "passing"
Html.text "build"
Html.text "0.5.0"
Html.text "npm"
Html.text " World "
Html.text " Hello "
Html.text " Bar "
Html.text " Large "
Html.text " Medium "
Html.text " Dark "
Html.text " Light "
Html.text " Black "
Html.text " White "
Html.text " Danger "
Html.text " Warning "
Html.text " Success "
Html.text " Info "
Html.text " Link "
Html.text " Primary "
Html.hr []
Html.text " Tag "
Html.text " Twelve "
Html.text " Eleven "
Html.text " Ten "
Html.text " Nine "
Html.text " Eight "
Html.text " Seven "
Html.text " Six "
Html.text " Five "
Html.text " Four "
Html.text " Three "
Html.text " Two "
Html.text " One "
Html.text " "
Html.text " Twelve "
Html.text " Eleven "
Html.text " Ten "
Html.text " Nine "
Html.text " Eight "
Html.text " Seven "
Html.text " Six "
Html.text " Five "
Html.text " Four "
Html.text " Three "
Html.text " Two "
Html.text " One "
Html.text " "
Html.text " Four "
Html.text " Three "
Html.text " Two "
Html.text " One "
Html.text " "
Html.text " Twelve "
Html.text " Eleven "
Html.text " Ten "
Html.text " Nine "
Html.text " Eight "
Html.text " Seven "
Html.text " Six "
Html.text " Five "
Html.text " Four "
Html.text " Three "
Html.text " Two "
Html.text " One "
Html.text " "
Html.text " Football League Championship "
Html.text " Relegation to the "
Html.text " 17 "
Html.text " −49 "
Html.text " 76 "
Html.text " 27 "
Html.text " 27 "
Html.text " 8 "
Html.text " 3 "
Html.text " 38 "
Html.text " (R) "
Html.text " Aston Villa "
Html.text " 20 "
Html.text " Football League Championship "
Html.text " Relegation to the "
Html.text " 34 "
Html.text " −28 "
Html.text " 67 "
Html.text " 39 "
Html.text " 22 "
Html.text " 7 "
Html.text " 9 "
Html.text " 38 "
Html.text " (R) "
Html.text " Norwich City "
Html.text " 19 "
Html.text " Football League Championship "
Html.text " Relegation to the "
Html.text " 37 "
Html.text " −21 "
Html.text " 65 "
Html.text " 44 "
Html.text " 19 "
Html.text " 10 "
Html.text " 9 "
Html.text " 38 "
Html.text " (R) "
Html.text " Newcastle United "
Html.text " 18 "
Html.text " 39 "
Html.text " −14 "
Html.text " 62 "
Html.text " 48 "
Html.text " 17 "
Html.text " 12 "
Html.text " 9 "
Html.text " 38 "
Html.text " Sunderland "
Html.text " 17 "
Html.text " 42 "
Html.text " −22 "
Html.text " 67 "
Html.text " 45 "
Html.text " 18 "
Html.text " 9 "
Html.text " 11 "
Html.text " 38 "
Html.text " AFC Bournemouth "
Html.text " 16 "
Html.text " 42 "
Html.text " −12 "
Html.text " 51 "
Html.text " 39 "
Html.text " 18 "
Html.text " 9 "
Html.text " 11 "
Html.text " 38 "
Html.text " Crystal Palace "
Html.text " 15 "
Html.text " 43 "
Html.text " −14 "
Html.text " 48 "
Html.text " 34 "
Html.text " 15 "
Html.text " 13 "
Html.text " 10 "
Html.text " 38 "
Html.text " West Bromwich Albion "
Html.text " 14 "
Html.text " 45 "
Html.text " −10 "
Html.text " 50 "
Html.text " 40 "
Html.text " 17 "
Html.text " 9 "
Html.text " 12 "
Html.text " 38 "
Html.text " Watford "
Html.text " 13 "
Html.text " 47 "
Html.text " −10 "
Html.text " 52 "
Html.text " 42 "
Html.text " 15 "
Html.text " 11 "
Html.text " 12 "
Html.text " 38 "
Html.text " Swansea City "
Html.text " 12 "
Html.text " 47 "
Html.text " +4 "
Html.text " 55 "
Html.text " 59 "
Html.text " 13 "
Html.text " 14 "
Html.text " 11 "
Html.text " 38 "
Html.text " Everton "
Html.text " 11 "
Html.text " 50 "
Html.text " +6 "
Html.text " 53 "
Html.text " 59 "
Html.text " 12 "
Html.text " 14 "
Html.text " 12 "
Html.text " 38 "
Html.text " Chelsea "
Html.text " 10 "
Html.text " 51 "
Html.text " −14 "
Html.text " 55 "
Html.text " 41 "
Html.text " 15 "
Html.text " 9 "
Html.text " 14 "
Html.text " 38 "
Html.text " Stoke City "
Html.text " 9 "
Html.text " 60 "
Html.text " +13 "
Html.text " 50 "
Html.text " 63 "
Html.text " 10 "
Html.text " 12 "
Html.text " 16 "
Html.text " 38 "
Html.text " Liverpool "
Html.text " 8 "
Html.text " Europa League third qualifying round "
Html.text " Qualification for the "
Html.text " 62 "
Html.text " +14 "
Html.text " 51 "
Html.text " 65 "
Html.text " 8 "
Html.text " 14 "
Html.text " 16 "
Html.text " 38 "
Html.text " West Ham United "
Html.text " 7 "
Html.text " Europa League group stage "
Html.text " Qualification for the "
Html.text " 63 "
Html.text " +18 "
Html.text " 41 "
Html.text " 59 "
Html.text " 11 "
Html.text " 9 "
Html.text " 18 "
Html.text " 38 "
Html.text " Southampton "
Html.text " 6 "
Html.text " Europa League group stage "
Html.text " Qualification for the "
Html.text " 66 "
Html.text " +14 "
Html.text " 35 "
Html.text " 49 "
Html.text " 10 "
Html.text " 9 "
Html.text " 19 "
Html.text " 38 "
Html.text " Manchester United "
Html.text " 5 "
Html.text " Champions League play-off round "
Html.text " Qualification for the "
Html.text " 66 "
Html.text " +30 "
Html.text " 41 "
Html.text " 71 "
Html.text " 10 "
Html.text " 9 "
Html.text " 19 "
Html.text " 38 "
Html.text " Manchester City "
Html.text " 4 "
Html.text " Champions League group stage "
Html.text " Qualification for the "
Html.text " 70 "
Html.text " +34 "
Html.text " 35 "
Html.text " 69 "
Html.text " 6 "
Html.text " 13 "
Html.text " 19 "
Html.text " 38 "
Html.text " Tottenham Hotspur "
Html.text " 3 "
Html.text " Champions League group stage "
Html.text " Qualification for the "
Html.text " 71 "
Html.text " +29 "
Html.text " 36 "
Html.text " 65 "
Html.text " 7 "
Html.text " 11 "
Html.text " 20 "
Html.text " 38 "
Html.text " Arsenal "
Html.text " 2 "
Html.text " Champions League group stage "
Html.text " Qualification for the "
Html.text " 81 "
Html.text " +32 "
Html.text " 36 "
Html.text " 68 "
Html.text " 3 "
Html.text " 12 "
Html.text " 23 "
Html.text " 38 "
Html.text " (C) "
Html.text " Leicester City "
Html.text " 1 "
Html.text " Qualification or relegation "
Html.text " Pts "
Html.text " GD "
Html.text " GA "
Html.text " GF "
Html.text " L "
Html.text " D "
Html.text " W "
Html.text " Pld "
Html.text " Team "
Html.text " Pos "
Html.text " Qualification or relegation "
Html.text " Pts "
Html.text " GD "
Html.text " GA "
Html.text " GF "
Html.text " L "
Html.text " D "
Html.text " W "
Html.text " Pld "
Html.text " Team "
Html.text " Pos "
Html.hr []
Html.text " Table "
Html.text "60%"
Html.text "45%"
Html.text "30%"
Html.text "15%"
Html.text "Indeterminate"
Html.text " 60% "
Html.text " 45% "
Html.text " 30% "
Html.text " 15% "
Html.text " 15% "
Html.text " 15% "
Html.text " 15% "
Html.text " 15% "
Html.text " 15% "
Html.text " 15% "
Html.text " 15% "
Html.hr []
Html.text " Progress bars "
Html.text " adipiscing elit lorem ipsum dolor sit amet, consectetur adipiscing elit "
Html.text "consectetur"
Html.text " Lorem ipsum dolor sit amet, "
Html.text " adipiscing elit lorem ipsum dolor sit amet, consectetur adipiscing elit "
Html.text "consectetur"
Html.text " Lorem ipsum dolor sit amet, "
Html.text " adipiscing elit lorem ipsum dolor sit amet, consectetur adipiscing elit "
Html.text "consectetur"
Html.text " Lorem ipsum dolor sit amet, "
Html.text " adipiscing elit lorem ipsum dolor sit amet, consectetur adipiscing elit "
Html.text "consectetur"
Html.text " Lorem ipsum dolor sit amet, "
Html.text " adipiscing elit lorem ipsum dolor sit amet, consectetur adipiscing elit "
Html.text "consectetur"
Html.text " Lorem ipsum dolor sit amet, "
Html.text " adipiscing elit lorem ipsum dolor sit amet, consectetur adipiscing elit "
Html.text "consectetur"
Html.text " Lorem ipsum dolor sit amet, "
Html.text " adipiscing elit lorem ipsum dolor sit amet, consectetur adipiscing elit "
Html.text "consectetur"
Html.text " Lorem ipsum dolor sit amet, "
Html.hr []
Html.text " Notifications "
Html.img [
    prop.src "https://s3.amazonaws.com/uifaces/faces/twitter/zeldman/128.jpg"
]
Html.hr []
Html.text " Images "
Html.hr []
Html.text " Icons "
Html.text " Search "
Html.input [
    prop.className "input"
    prop.type' "text"
    prop.placeholder "Find a repository"
]
Html.text "Choose"
Html.text "Venezuela"
Html.text "Uruguay"
Html.text "Suriname"
Html.text "Peru"
Html.text "Paraguay"
Html.text "Guyana"
Html.text "Ecuador"
Html.text "Colombia"
Html.text "Chile"
Html.text "Brazil"
Html.text "Bolivia"
Html.text "Argentina"
Html.text " Transfer "
Html.input [
    prop.className "input"
    prop.type' "text"
    prop.placeholder "Amount of money"
]
Html.text "€"
Html.text "£"
Html.text "$"
Html.text " Transfer "
Html.input [
    prop.className "input"
    prop.type' "text"
    prop.placeholder "Amount of money"
]
Html.text "€"
Html.text "£"
Html.text "$"
Html.text " Search "
Html.input [
    prop.classes [ "input"; "is-large" ]
    prop.type' "text"
    prop.placeholder "Find a repository"
]
Html.text " Search "
Html.input [
    prop.className "input"
    prop.type' "text"
    prop.placeholder "Find a repository"
]
Html.hr []
Html.text " Form addons "
Html.text " "
Html.text " Login "
Html.input [
    prop.className "input"
    prop.type' "password"
    prop.placeholder "Password"
]
Html.input [
    prop.className "input"
    prop.type' "email"
    prop.placeholder "Email"
]
Html.hr []
Html.text " With Font Awesome icons "
Html.text " "
Html.input [
    prop.classes [ "input"; "is-large" ]
    prop.type' "email"
    prop.placeholder "Email"
]
Html.input [
    prop.classes [ "input"; "is-large" ]
    prop.type' "email"
    prop.placeholder "Email"
]
Html.input [
    prop.classes [ "input"; "is-large" ]
    prop.type' "email"
    prop.placeholder "Email"
]
Html.input [
    prop.classes [ "input"; "is-large" ]
    prop.type' "email"
    prop.placeholder "Email"
]
Html.text "Large input"
Html.input [
    prop.classes [ "input"; "is-medium" ]
    prop.type' "email"
    prop.placeholder "Email"
]
Html.input [
    prop.classes [ "input"; "is-medium" ]
    prop.type' "email"
    prop.placeholder "Email"
]
Html.input [
    prop.classes [ "input"; "is-medium" ]
    prop.type' "email"
    prop.placeholder "Email"
]
Html.text "Medium input"
Html.input [
    prop.className "input"
    prop.type' "email"
    prop.placeholder "Email"
]
Html.input [
    prop.className "input"
    prop.type' "email"
    prop.placeholder "Email"
]
Html.text "Normal input"
Html.input [
    prop.classes [ "input"; "is-small" ]
    prop.type' "email"
    prop.placeholder "Email"
]
Html.text "Small input"
Html.text "With options"
Html.text "Select dropdown"
Html.text "With options"
Html.text "Select dropdown"
Html.text "With options"
Html.text "Select dropdown"
Html.text "With options"
Html.text "Select dropdown"
Html.input [
    prop.classes [ "input"; "is-large" ]
    prop.type' "text"
    prop.placeholder "Large input"
]
Html.input [
    prop.classes [ "input"; "is-medium" ]
    prop.type' "text"
    prop.placeholder "Medium input"
]
Html.input [
    prop.className "input"
    prop.type' "text"
    prop.placeholder "Normal input"
]
Html.input [
    prop.classes [ "input"; "is-small" ]
    prop.type' "text"
    prop.placeholder "Small input"
]
Html.hr []
Html.text " Sizes "
Html.text " "
Html.input [
    prop.classes [ "input"; "is-danger" ]
    prop.type' "text"
    prop.placeholder "Danger input"
]
Html.input [
    prop.classes [ "input"; "is-warning" ]
    prop.type' "text"
    prop.placeholder "Warning input"
]
Html.input [
    prop.classes [ "input"; "is-success" ]
    prop.type' "text"
    prop.placeholder "Success input"
]
Html.input [
    prop.classes [ "input"; "is-info" ]
    prop.type' "text"
    prop.placeholder "Info input"
]
Html.input [
    prop.classes [ "input"; "is-primary" ]
    prop.type' "text"
    prop.placeholder "Primary input"
]
Html.hr []
Html.text " Colors "
Html.text " "
Html.input [
    prop.classes [ "input"; "is-rounded" ]
    prop.type' "text"
    prop.placeholder "Rounded input"
]
Html.hr []
Html.text " Styles "
Html.text " "
Html.text " Screen Shot 2017-07-29 at 15.54.25.png "
Html.text " Danger file… "
Html.input [
    prop.className "file-input"
    prop.type' "file"
    prop.name "resume"
]
Html.text " Warning file… "
Html.input [
    prop.className "file-input"
    prop.type' "file"
    prop.name "resume"
]
Html.text " Screen Shot 2017-07-29 at 15.54.25.png "
Html.text " Info file… "
Html.input [
    prop.className "file-input"
    prop.type' "file"
    prop.name "resume"
]
Html.text " Primary file… "
Html.input [
    prop.className "file-input"
    prop.type' "file"
    prop.name "resume"
]
Html.text " Screen Shot 2017-07-29 at 15.54.25.png "
Html.text " Choose a file… "
Html.input [
    prop.className "file-input"
    prop.type' "file"
    prop.name "resume"
]
Html.text " Choose a file… "
Html.input [
    prop.className "file-input"
    prop.type' "file"
    prop.name "resume"
]
Html.hr []
Html.text "File"
Html.text " "
Html.text " Send message "
Html.text "Question"
Html.text " This field is required "
Html.input [
    prop.classes [ "input"; "is-danger" ]
    prop.type' "text"
    prop.placeholder "e.g. Partnership opportunity"
]
Html.text "Subject"
Html.text " No "
Html.input [
    prop.type' "radio"
    prop.name "member"
]
Html.text " Yes "
Html.input [
    prop.type' "radio"
    prop.name "member"
]
Html.text "Already a member?"
Html.text "Relationship"
Html.text "Management"
Html.text "Development"
Html.text "Science computer"
Html.text "Skills"
Html.text "Sales"
Html.text "Marketing"
Html.text "Business development"
Html.text "Department"
Html.text "This email is correct"
Html.input [
    prop.classes [ "input"; "is-success" ]
    prop.type' "email"
    prop.placeholder "Email"
    prop.value true
]
Html.input [
    prop.className "input"
    prop.type' "text"
    prop.placeholder "Name"
]
Html.text "From"
Html.hr []
Html.text " Horizontal Form "
Html.text " "
Html.text " Cancel "
Html.text " Submit "
Html.text " No "
Html.input [
    prop.disabled true
    prop.name "question"
    prop.type' "radio"
]
Html.text " Yes "
Html.input [
    prop.disabled true
    prop.name "question"
    prop.type' "radio"
]
Html.text " Remember me "
Html.input [
    prop.disabled true
    prop.type' "checkbox"
]
Html.input [
    prop.className "input"
    prop.disabled true
    prop.placeholder "Disabled input"
    prop.type' "text"
]
Html.hr []
Html.text " Disabled "
Html.text " "
Html.text "Cancel"
Html.text "Submit"
Html.text " No "
Html.input [
    prop.type' "radio"
    prop.name "question"
]
Html.text " Yes "
Html.input [
    prop.type' "radio"
    prop.name "question"
]
Html.text "terms and conditions"
Html.text " I agree to the "
Html.input [
    prop.type' "checkbox"
]
Html.text "Message"
Html.text "With options"
Html.text "Select dropdown"
Html.text "Files to join"
Html.text "With options"
Html.text "Select dropdown"
Html.text "Subject"
Html.text "This email is invalid"
Html.input [
    prop.classes [ "input"; "is-danger" ]
    prop.type' "text"
    prop.placeholder "Email input"
    prop.value true
]
Html.text "Email"
Html.text "This username is available"
Html.input [
    prop.classes [ "input"; "is-success" ]
    prop.type' "text"
    prop.placeholder "Text input"
    prop.value true
]
Html.text "Username"
Html.input [
    prop.className "input"
    prop.type' "text"
    prop.placeholder "Text input"
]
Html.text "Name"
Html.hr []
Html.text " Form "
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque risus mi, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum felis venenatis efficitur. Aenean ac eleifend lacus, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula, id porttitor mi magna a neque. Donec dui urna, vehicula et sem eget, facilisis sodales sem. "
Html.text " Info "
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit lorem ipsum dolor sit amet, consectetur adipiscing elit "
Html.text " Hello World "
Html.hr []
Html.text " Delete "
Html.text " Cras in nibh lacinia, venenatis nisi et, auctor urna. Donec pulvinar lacus sed diam dignissim, ut eleifend eros accumsan. Phasellus non tortor eros. Ut sed rutrum lacus. Etiam purus nunc, scelerisque quis enim vitae, malesuada ultrices turpis. Nunc vitae maximus purus, nec consectetur dui. Suspendisse euismod, elit vel rutrum commodo, ipsum tortor maximus dui, sed varius sapien odio vitae est. Etiam at cursus metus. "
Html.text " Sixth level "
Html.text " Aliquam sagittis rhoncus vulputate. Cras non luctus sem, sed tincidunt ligula. Vestibulum at nunc elit. Praesent aliquet ligula mi, in luctus elit volutpat porta. Phasellus molestie diam vel nisi sodales, a eleifend augue laoreet. Sed nec eleifend justo. Nam et sollicitudin odio. "
Html.text " Fifth level "
Html.text " Phasellus porttitor enim id metus volutpat ultricies. Ut nisi nunc, blandit sed dapibus at, vestibulum in felis. Etiam iaculis lorem ac nibh bibendum rhoncus. Nam interdum efficitur ligula sit amet ullamcorper. Etiam tristique, leo vitae porta faucibus, mi lacus laoreet metus, at cursus leo est vel tellus. Sed ac posuere est. Nunc ultricies nunc neque, vitae ultricies ex sodales quis. Aliquam eu nibh in libero accumsan pulvinar. Nullam nec nisl placerat, pretium metus vel, euismod ipsum. Proin tempor cursus nisl vel condimentum. Nam pharetra varius metus non pellentesque. "
Html.text " Twelve "
Html.text " Eleven "
Html.text " Ten "
Html.text " Nine "
Html.text " Eight "
Html.text " Seven "
Html.text " Six "
Html.text " Five "
Html.text " Four "
Html.text " Three "
Html.text " Two "
Html.text " One "
Html.text " Maecenas eleifend sollicitudin dui faucibus sollicitudin augue cursus non. Ut finibus eleifend arcu ut vehicula. Mauris eu est maximus est porta condimentum in eu justo. Nulla id iaculis sapien. "
Html.text " Nulla efficitur eleifend nisi, sit amet bibendum sapien fringilla ac. Mauris euismod metus a tellus laoreet, at elementum ex efficitur. "
Html.text " Fourth level "
Html.text " Suspendisse egestas sapien non felis placerat elementum. Morbi tortor nisl, suscipit sed mi sit amet, mollis malesuada nulla. Nulla facilisi. Nullam ac erat ante. "
Html.text " Sed sagittis enim ac tortor maximus rutrum. Nulla facilisi. Donec mattis vulputate risus in luctus. Maecenas vestibulum interdum commodo. "
Html.text " elementum. Maecenas ultrices lacus quis neque consectetur, et lobortis nisi molestie. "
Html.text " justo sodales "
Html.text " Quisque at semper enim, eu hendrerit odio. Etiam auctor nisl et "
Html.text " Ut venenatis, nisl scelerisque sollicitudin fermentum, quam libero hendrerit ipsum, ut blandit est tellus sit amet turpis. "
Html.text " Vivamus maximus ultricies pulvinar. "
Html.text " Quisque aliquam cursus urna, non bibendum massa viverra eget. "
Html.text " Aenean nec tortor orci. "
Html.text " Donec a diam tellus. "
Html.text " Integer in volutpat libero. "
Html.text " Cras gravida arcu at diam gravida gravida. "
Html.text " Donec blandit a lorem id convallis. "
Html.text ". Phasellus lacus ex, semper ac tortor nec, fringilla condimentum orci. Fusce eu rutrum tellus. "
Html.text " non ante "
Html.text " Quisque ante lacus, malesuada ac auctor vitae, congue "
Html.text " Third level "
Html.text " Ut non enim metus. "
Html.text " Aliquam nec felis in sapien venenatis viverra fermentum nec lectus. "
Html.text " Morbi eu nulla lobortis, lobortis est in, fringilla felis. "
Html.text " In fermentum leo eu lectus mollis, quis dictum mi aliquet. "
Html.text " blandit. Quisque condimentum maximus mi, sit amet commodo arcu rutrum id. Proin pretium urna vel cursus venenatis. Suspendisse potenti. Etiam mattis sem rhoncus lacus dapibus facilisis. Donec at dignissim dui. Ut et neque nisl. "
Html.text " augue tincidunt "
Html.text " Curabitur accumsan turpis pharetra "
Html.text " Second level "
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan, metus ultrices eleifend gravida, nulla nunc varius lectus, nec rutrum justo nibh eu lectus. Ut vulputate semper dui. Fusce erat odio, sollicitudin vel erat vel, interdum mattis neque. "
Html.text " Hello World "
Html.hr []
Html.text " Content "
Html.text " GitHub "
Html.text " GitHub "
Html.text " GitHub "
Html.text " GitHub "
Html.text " Inverted "
Html.text " Inverted "
Html.text " Inverted "
Html.text " Inverted "
Html.text " Invert Outlined "
Html.text " Invert Outlined "
Html.text " Invert Outlined "
Html.text " Invert Outlined "
Html.text " Outlined "
Html.text " Outlined "
Html.text " Outlined "
Html.text " Outlined "
Html.text " Outlined "
Html.text " Large "
Html.text " Medium "
Html.text " Normal "
Html.text " Small "
Html.text "Rounded"
Html.text "Rounded"
Html.text "Rounded"
Html.text "Rounded"
Html.text "Rounded"
Html.text "Rounded"
Html.text "Right"
Html.text "Center"
Html.text "Left"
Html.text "Underline"
Html.text "Italic"
Html.text "Bold"
Html.text " Delete "
Html.text " Save "
Html.text " Twitter "
Html.text " GitHub "
Html.text " Loading "
Html.text " Loading "
Html.text " Loading "
Html.text " Loading "
Html.text " Loading "
Html.text " Loading "
Html.text " Active "
Html.text " Active "
Html.text " Active "
Html.text " Active "
Html.text " Active "
Html.text " Active "
Html.text " Hover "
Html.text " Hover "
Html.text " Hover "
Html.text " Hover "
Html.text " Hover "
Html.text " Hover "
Html.text " Focus "
Html.text " Focus "
Html.text " Focus "
Html.text " Focus "
Html.text " Focus "
Html.text " Focus "
Html.text " Danger "
Html.text " Warning "
Html.text " Success "
Html.text " Info "
Html.text " Primary "
Html.text " Link "
Html.text " Link "
Html.text " Black "
Html.text " Dark "
Html.text " Light "
Html.text " White "
Html.text " Button "
Html.hr []
Html.text " Button "
Html.text " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean efficitur sit amet massa fringilla egestas. Nullam condimentum luctus turpis. "
Html.text " "
Html.text " 31m "
Html.text " @johnsmith "
Html.text " John Smith "
Html.img [
    prop.alt "Image"
    prop.src "https://s3.amazonaws.com/uifaces/faces/twitter/zeldman/128.jpg"
]
Html.hr []
Html.text " Box "
Html.text " Subtitle 5 "
Html.text " Title 3 "
Html.text " Subtitle 4 "
Html.text " Title 2 "
Html.text " Subtitle 3 "
Html.text " Title 1 "
Html.text " Subtitle "
Html.text " Title "
Html.text " Subtitle 6 "
Html.text " Subtitle 5 "
Html.text " Subtitle 4 "
Html.text " Subtitle 3 "
Html.text " Subtitle 2 "
Html.text " Subtitle 1 "
Html.text " Title 6 "
Html.text " Title 5 "
Html.text " Title 4 "
Html.text " Title 3 "
Html.text " Title 2 "
Html.text " Title 1 "
Html.hr []
Html.text " Typography"